/**
 * Authoring entrypoint for whatsapp-tools.
 *
 * Production deploys the gzip loader generated by scripts/bundle-whatsapp-tools.mjs.
 * The minified bundle lives in private.edge_fn_bundles (name: whatsapp-tools) and is
 * fetched at runtime via get_edge_fn_bundle. Do not treat this thin file as the live
 * v11 implementation by itself — the canonical source is this handler plus
 * `_shared/whatsapp-tools-http.ts`, `_shared/whatsapp-inbox-ingest.ts`, and
 * `_shared/whatsapp-agent/tools.ts`.
 */
import { handleWhatsAppToolsRequest } from "../_shared/whatsapp-tools-http.ts";

Deno.serve(handleWhatsAppToolsRequest);
